rabbitmq:
  image: rabbitmq
  expose:
    - 15672
asterisk:
  image: safchain/asterisk-consul-amqp
  links:
    - consul
    - rabbitmq
  expose:
    - 8888
consul:
  image: consul
  ports:
    - "8500:8500"
  environment:
    - CONSUL_BIND_INTERFACE=eth0
kamailio:
  image: kamailio/kamailio:5.3.1-buster
  links:
    - consul
    - asterisk
  ports:
    - "5060:5060/udp"
  expose:
    - 5060/udp
